# Generated by Django 5.0.6 on 2024-07-02 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=100)),
                ('current_city', models.CharField(max_length=100)),
                ('rent_per_hr', models.IntegerField()),
                ('rent_history', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('hours_requirement', models.IntegerField()),
                ('total_payable_amt', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
            ],
        ),
        migrations.CreateModel(
            name='RentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.rent')),
            ],
        ),
    ]
